### ISSUE TITLE
Error while training

### ISSUE THREAD

**Issue by bbbts** [chenller/mmseg-extension#2]
Getting this error - 
AssertionError: MMCV==2.2.0 is used but incompatible. Please install mmcv>=2.0.0rc4.
Was anyone able to solve it?
Thanks!

**Comment by chenller** [comment]
Based on my testing, I believe this is an issue with the MMSEG repository. I will provide a solution later.

**Comment by bbbts** [comment]
> Based on my testing, I believe this is an issue with the MMSEG repository. I will provide a solution later.

Thanks in advance! Looking forward to it.

**Comment by chenller** [comment]
This error is caused by the `mmseg` repository not supporting `mmcv==2.2.0`. Please install according to [get_started.md](https://github.com/chenller/mmseg-extension/blob/main/docs/readme/get_started.md).
*Main changes:*
[python=3.9](https://github.com/chenller/mmseg-extension/blob/main/docs/readme/get_started.md?plain=1#L20)
[pytorch==2.1.x](https://github.com/chenller/mmseg-extension/blob/main/docs/readme/get_started.md?plain=1#L30)
[mmcv==2.1.0](https://github.com/chenller/mmseg-extension/blob/main/docs/readme/get_started.md?plain=1#L45)
